#!/bin/bash

usage() {
  printf '%s\n' "Usage: install-pyenv [-h]
install-pyenv installs pyenv and the latest Python version.

where:
  -h, --help  - show this help text"
}

main() {
  # Install dependencies
  sudo apt-get install -y \
    make \
    build-essential \
    libssl-dev \
    zlib1g-dev \
    libbz2-dev \
    libreadline-dev \
    libsqlite3-dev \
    wget \
    curl \
    llvm \
    libncursesw5-dev \
    xz-utils \
    tk-dev \
    libxml2-dev \
    libxmlsec1-dev \
    libffi-dev \
    liblzma-dev

  # Install pyenv
  curl https://pyenv.run | bash

  # Refresh bash
  source refresh_bash

  # Install latest python
  pyenv install 3:latest
}

# Option parsing
declare PARAMS=""
while (( "$#" )); do
  case $1 in
    -h|--help)  # display help message
      usage
      exit 1
      ;;
    --)  # End argument parsing
      shift
      break
      ;;
    -*|--*)  # unsupported flags
      echo "Unsupported flag: $1" >&2
      usage
      exit 1
      ;;
    *)  # preserve positional arguments
      PARAMS="${PARAMS} $1"
      shift
      ;;
  esac
done

# set positional arguments in their proper place
eval set -- "${PARAMS}"

# Freeze configuration flags
# readonly SOME_FLAG

main "$@"

