#!/bin/bash

usage() {
  printf '%s\n' "Usage: install-nvm [-h]
install-nvm installs NVM and the latest node LTS 

where:
  -h, --help  - show this help text"
}

main() {
  # Install nvm
  PROFILE=/dev/null bash -c 'curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.1/install.sh | bash'

  # Refresh bash
  rb

  # Install latest node
  nvm install --lts 
}

# Option parsing
declare PARAMS=""
declare SOME_FLAG='false'
while (( "$#" )); do
  case $1 in
    -h|--help)  # display help message
      usage
      exit 1
      ;;
    --)  # End argument parsing
      shift
      break
      ;;
    -*|--*)  # unsupported flags
      echo "Unsupported flag: $1" >&2
      usage
      exit 1
      ;;
    *)  # preserve positional arguments
      PARAMS="${PARAMS} $1"
      shift
      ;;
  esac
done

# set positional arguments in their proper place
eval set -- "${PARAMS}"

# Freeze configuration flags
readonly SOME_FLAG

main "$@"

