#!/bin/bash

usage() {
  printf '%s\n' "Usage: todo-copilot [-h]
todo-copilot writes a TODO entry to get vim-copilot started.

where:
  -h, --help  - show this help text"
}

main() {
  if [[ -z "${UBUNTU_SETUP_TODO}" ]]; then
    printf '%s\n' \
"---COPILOT---
1. Open vim: vim
2. Run the following command: :Copilot setup
3. Follow the instructions to set up vim-copilot" \
    >> "${UBUNTU_SETUP_TODO}"
  fi
}

# Option parsing
declare PARAMS=""
while (( "$#" )); do
  case $1 in
    -h|--help)  # display help message
      usage
      exit 1
      ;;
    --)  # End argument parsing
      shift
      break
      ;;
    -*|--*)  # unsupported flags
      echo "Unsupported flag: $1" >&2
      usage
      exit 1
      ;;
    *)  # preserve positional arguments
      PARAMS="${PARAMS} $1"
      shift
      ;;
  esac
done

# set positional arguments in their proper place
eval set -- "${PARAMS}"

# Freeze configuration flags
# readonly SOME_FLAG

main "$@"
