#!/bin/bash

usage() {
  printf '%s\n' "Usage: configure-tpm [-h]
configure-tpm gets the tpm tmux plugin manager ready to go.

where:
  -h, --help  - show this help text"
}

main() {
  # Install TPM
  git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm

  # Start an unattached tmux server
  tmux start-server

  # Create a new session but don't attach to it either
  tmux new-session -d

  # Execute script that installs plugins
  ~/.tmux/plugins/tpm/scripts/install_plugins.sh

  # Kill the server (which also kills the session)
  tmux kill-server
}

# Option parsing
declare PARAMS=""
while (( "$#" )); do
  case $1 in
    -h|--help)  # display help message
      usage
      exit 1
      ;;
    --)  # End argument parsing
      shift
      break
      ;;
    -*|--*)  # unsupported flags
      echo "Unsupported flag: $1" >&2
      usage
      exit 1
      ;;
    *)  # preserve positional arguments
      PARAMS="${PARAMS} $1"
      shift
      ;;
  esac
done

# set positional arguments in their proper place
eval set -- "${PARAMS}"

# Freeze configuration flags
# readonly SOME_FLAG

main "$@"
